---
name: Polars data handling
author: Arne Tarara <arne@green-coding.io>
description: Use Polars for a file import and column operations

services:
  polars:
    image: python:3.13.0-slim-bookworm
    setup-commands:
      - pip install polars==1.9.0

flow:
  - name: Polars Warmup
    container: polars
    commands:
      - type: console
        command: python3 /tmp/repo/polars_test.py

  - name: Polars GO
    container: polars
    commands:
      - type: console
        command: python3 /tmp/repo/polars_test.py
